### ISSUE TITLE
incompatibility with webpack 

### ISSUE THREAD

**Issue by chauhan-saurabh** [EddyVerbruggen/nativescript-nodeify#37] opened 2018-03-23 07:04 UTC
Cannot find module '/Users/saurabh.chauhan/Desktop/cognito/shyftCognito/platforms/ios/shyftCognito/app/tns_modules/nativescript-nodeify/patch-npm-packages.js'

**Comment by EddyVerbruggen** [comment] 2018-03-24 14:01
Duplicate of #35

**Closed by EddyVerbruggen** 2018-03-24 14:01 UTC
