### ISSUE TITLE
Build fails when using aws-sdk and webpack 

### ISSUE THREAD

**Issue by surdu** [EddyVerbruggen/nativescript-nodeify#36] opened 2018-03-08 13:40 UTC
We've enabled webpack for our project as specified in the NS documentation, but the bundling fails with the following error:

```
ERROR in ../node_modules/xml2js/lib/xml2js.js
Module not found: Error: Can't resolve 'timers' in '/Users/nicolae.surdu/work/theproject/node_modules/xml2js/lib'

 @ ../node_modules/xml2js/lib/xml2js.js 19:17-34
 @ ../node_modules/aws-sdk/lib/xml/node_parser.js
 @ ../node_modules/aws-sdk/lib/node_loader.js
 @ ../node_modules/aws-sdk/lib/aws.js
 @ ./services/aws/loginService.js
 @ ./services/aws/aws.js
 @ ./app.js
```

I didn't manage to find anythong about this issue on Google, but I have a fuzzy feeling it fails because `nodescript-nodeify` didn't get to do it's magic.

Am I worng assuming this ?

**Comment by EddyVerbruggen** [comment] 2018-03-08 13:41
Dupe of #35

**Closed by EddyVerbruggen** 2018-03-08 13:41 UTC
